FROM node:17-alpine as base

FROM base AS runner
WORKDIR /usr/src/app

COPY package.json yarn.lock ./
RUN yarn install --immutable

ENV NODE_ENV="production"
ENV NODE_OPTIONS="--enable-source-maps --experimental-fetch"

COPY . .

RUN yarn build
CMD yarn start
